//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibClientWinform.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVelibService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/getCities", ReplyAction="http://tempuri.org/IVelibService/getCitiesResponse")]
        string getCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/getCities", ReplyAction="http://tempuri.org/IVelibService/getCitiesResponse")]
        System.Threading.Tasks.Task<string> getCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SearchStations", ReplyAction="http://tempuri.org/IVelibService/SearchStationsResponse")]
        string SearchStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SearchStations", ReplyAction="http://tempuri.org/IVelibService/SearchStationsResponse")]
        System.Threading.Tasks.Task<string> SearchStationsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SearchBikeNum", ReplyAction="http://tempuri.org/IVelibService/SearchBikeNumResponse")]
        string SearchBikeNum(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SearchBikeNum", ReplyAction="http://tempuri.org/IVelibService/SearchBikeNumResponse")]
        System.Threading.Tasks.Task<string> SearchBikeNumAsync(string city, string station);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : VelibClientWinform.ServiceReference1.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<VelibClientWinform.ServiceReference1.IVelibService>, VelibClientWinform.ServiceReference1.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getCities() {
            return base.Channel.getCities();
        }
        
        public System.Threading.Tasks.Task<string> getCitiesAsync() {
            return base.Channel.getCitiesAsync();
        }
        
        public string SearchStations(string city) {
            return base.Channel.SearchStations(city);
        }
        
        public System.Threading.Tasks.Task<string> SearchStationsAsync(string city) {
            return base.Channel.SearchStationsAsync(city);
        }
        
        public string SearchBikeNum(string city, string station) {
            return base.Channel.SearchBikeNum(city, station);
        }
        
        public System.Threading.Tasks.Task<string> SearchBikeNumAsync(string city, string station) {
            return base.Channel.SearchBikeNumAsync(city, station);
        }
    }
}
